version: '3'
services:
  daq:
    build: ./daq
    volumes:
      - daq-data:/data
    networks:
      - app-network
    privileged: true

  api:
    build: ./api
    volumes:
      - daq-data:/data
    ports:
      - "5000:5000"
    networks:
      - app-network
  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html/
    networks:
      - app-network
    depends_on:
      - api

volumes:
  daq-data:

networks:
  app-network:
